# Root Netlify configuration for monorepo
# Deploy client frontend by default

[build]
  base = "apps/client-frontend"
  publish = "apps/client-frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Ignore Python API changes to prevent unnecessary rebuilds
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/api/"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200