# Stage 8: Prometheus Configuration
# PDF Industrial Pipeline - Monitoring Setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'pdf-industrial-pipeline'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PDF Pipeline Application
  - job_name: 'pdf-pipeline'
    static_configs:
      - targets: 
          - 'pdf-pipeline-1:8000'
          - 'pdf-pipeline-2:8000'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PDF Pipeline Health Checks
  - job_name: 'pdf-pipeline-health'
    static_configs:
      - targets: 
          - 'pdf-pipeline-1:8000'
          - 'pdf-pipeline-2:8000'
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Redis Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'pdf-pipeline-performance'
    static_configs:
      - targets: 
          - 'pdf-pipeline-1:8000'
          - 'pdf-pipeline-2:8000'
    metrics_path: '/performance/metrics'
    scrape_interval: 60s
    scrape_timeout: 30s

  # Cache metrics
  - job_name: 'pdf-pipeline-cache'
    static_configs:
      - targets: 
          - 'pdf-pipeline-1:8000'
          - 'pdf-pipeline-2:8000'
    metrics_path: '/performance/cache/stats'
    scrape_interval: 30s

  # ML Pipeline metrics
  - job_name: 'pdf-pipeline-ml'
    static_configs:
      - targets: 
          - 'pdf-pipeline-1:8000'
          - 'pdf-pipeline-2:8000'
    metrics_path: '/ml/stats'
    scrape_interval: 60s 