[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile.railway"

[deploy]
startCommand = "python main_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
PORT = "8000"
PYTHONPATH = "/app"
ENVIRONMENT = "production"
# SECRET_KEY should be set via Railway dashboard environment variables for security
DEBUG = "false"
API_VERSION = "v2"