[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api/Dockerfile.railway"

[deploy]
startCommand = "python main_simple.py"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
PORT = "8000"
PYTHONPATH = "/app"
ENVIRONMENT = "production"
SECRET_KEY = "abca14e8ad3982ae93c07c42b01daf57886355ca0702a58b6d94717942f78d09"
DEBUG = "false"
API_VERSION = "v2"