[build]
  publish = "dist"
  command = "npm run build"
  base = "apps/admin-frontend"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm run build:dev"